language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
# command to install dependencies
install:
  - python -m pip install pip==21.3.1 && pip install -r requirements.txt
script:
  - python test.py
